main.py:344: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  hps = yaml.load(config_file)
/home/hxie1/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:2479: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Current network: SurfSegNSBNet
loading unary network pretrain checkpoint: /home/hxie1/data/OCT_Beijing/netParameters/unet20191101/model_best_UNetPure_20191102.pth.tar
=> loaded unary network pretrain checkpoint (epoch 3826)
vol_list= None
training dataset length:1085
Epoch: 3827
Traceback (most recent call last):
  File "main.py", line 416, in <module>
    main()
  File "main.py", line 403, in main
    learn(model, hps)
  File "main.py", line 163, in learn
    m_batch_loss = train(model, loss_func, optimizer, batch, hps)
  File "main.py", line 59, in train
    loss.backward()
  File "/home/hxie1/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/hxie1/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.DoubleTensor [48, 512]], which is output 0 of AddBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
